environment:
  NugetApiKey:
    secure: Gxlox4/BGS+/9rX7ZRqAuA5bRzVFjYTKuyU8jpBbA5yfIzprQbzxZoAdhZxppRZ4

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# version: 1.0.{build}
build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build\build.ps1 -Task Deploy
